# NumPy

## Array 정의 및 사용하기

In [1]:
import numpy as np
 
list1 = [1, 2, 3, 4]
a = np.array(list1)
print(a.shape) 
 
b = np.array([[1,2,3],[4,5,6]])
print(b.shape) 
print(b[0,0])  

(4,)
(2, 3)
1


In [5]:
import numpy as np
 
a = np.zeros((2,2))
print(a)
 
a = np.ones((2,3))
print(a)
 
a = np.full((2,3), 5)
print(a)
 
a = np.eye(3)
print(a)
 
a = np.array(np.arange(20)).reshape((4,5))
print(a)

a = np.array(range(20)).reshape((4,5))
print(a)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## NumPy 슬라이싱

In [6]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
 
a = arr[0:2, 0:2]
print(a)
 
a = arr[1:, 1:]
print(a)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


## NumPy 정수 인덱싱
* a[[row1, row2], [col1, col2]] 와 같이 표현
* a[row1, col1] 과 a[row2, col2] 라는 두 개의 배열요소의 집합을 의미
* [row] 갯수는 1이거나 col의 갯수와 동일하게, [col] 도 마찬가지

In [27]:
import numpy as np
 
lst = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
a = np.array(lst)
 
#s = a[[0, 2], [1, 3]]
s = a[[0,1]] # row 0, row 1
print(s)
s = a[[1],[2,2,3]]
print(s)
s = a[[0,1,2],[2]]
print(s)

[[1 2 3 4]
 [5 6 7 8]]
[7 7 8]
[ 3  7 11]


## NumPy 부울린 인덱싱

In [28]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
 
bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
 
n = a[bool_indexing_array];
print(n)  

[2 4 6 8]


In [29]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
 
bool_indexing = (a % 2 == 0)
 
print(bool_indexing)

print(a[bool_indexing])

n = a[ a % 2 == 0 ]
print(n)

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]
