# NumPy

## NumPy 연산

In [1]:
import numpy as np
 
a = np.array([1,2,3])
b = np.array([4,5,6])
 
c = a + b
print(c)
 
c = a - b
print(c)
 
c = np.multiply(a, b)
print(c)
 
c = np.divide(a, b)
print(c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 브로드 캐스팅
* np.empty_like(x): returns array of uninitialized (arbitrary) data with the same shape and type as prototype.

In [3]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   
print(x)
print(v)
print(y)
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


* np.tile (v, reps): v array 를 tile 처럼 붙여서 다른 shape의 array로 만드는 것
* reps에 따라 모양이 바뀌는데, v 랑 reps의 dimension이 다르면, 1을 앞에 padding 시킨다. 
  * np.tile(x, (3,)): x는 2D, (3,)은 1D, (3,) -> (1,3) 으로 처리: 오른쪽으로 3개 붙이는 것

In [19]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  
print(vv)                 
y = x + vv  
print(y) 
vvv = np.tile( x, (3,))
print(vvv)
print(x.ndim)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 1  2  3  1  2  3  1  2  3]
 [ 4  5  6  4  5  6  4  5  6]
 [ 7  8  9  7  8  9  7  8  9]
 [10 11 12 10 11 12 10 11 12]]
2


* column 갯수가 같아야 함, 아니면 ValueError가 발생

In [22]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [25]:
import numpy as np

v = np.array([1,2,3])
w = np.array([4,5])  
print(np.reshape(v, (3,1))) # (3,1) * (1,2) = (3,2)
print(np.reshape(v, (3, 1)) * w)

x = np.array([[1,2,3], [4,5,6]])
print(x + v)

print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))

print(x * 2)

[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## 행렬 곱 연산

In [ ]:
import numpy as np
 
lst1 = [
    [1,2],
    [3,4]
]
 
lst2 = [
    [5,6],
    [7,8]
]
a = np.array(lst1)
b = np.array(lst2)
 
c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


## 행렬 전치
* Transposing a 1-D array returns an unchanged view of the original array.

In [38]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    
           
print(x.T)  
           

v = np.array([1,2,3])
print(v.shape)
print(v.ndim)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
(3,)
1
[1 2 3]


## 행렬 열간, 행간 통계

In [41]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
s = np.sum(a)
print(s)   
 
s = np.sum(a, axis=0) # c0lumn-wise
print(s)   
 
s = np.sum(a, axis=1) # 1row-wise
print(s)   
 
s = np.prod(a)
print(s)   
print(np.prod(a, axis=0))
print(np.prod(a, axis=1))

10
[4 6]
[3 7]
24
[3 8]
[ 2 12]
